In [2]:
import pandas as pd
import numpy as np

In [3]:
DT = pd.read_csv('my data/data.csv')

In [4]:
DT

FirstName LastName   Age  Sex preTestScore postTestScore location
0       abc      mno  12.0    m         90.0          65.0      NaN
1       NaN      NaN   NaN  NaN         90.0             ?      NaN
2       ghi      pqr  12.0    f            -          65.0        ?
3       jkl      stu  12.0    f         90.0          62.0      NaN
4       mno      vwx  12.0    m         89.0          63.0      NaN

In [5]:
DT.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   FirstName      4 non-null      object 
 1   LastName       4 non-null      object 
 2   Age            4 non-null      float64
 3   Sex            4 non-null      object 
 4   preTestScore   5 non-null      object 
 5   postTestScore  5 non-null      object 
 6   location       1 non-null      object 
dtypes: float64(1), object(6)
memory usage: 412.0+ bytes


In [6]:
DT.shape

(5, 7)

In [7]:
# creating missing values lists
missing_val = ['n/a','-','?']
DT = pd.read_csv('my data/data.csv', na_values=missing_val)

In [8]:
DT

FirstName LastName   Age  Sex  preTestScore  postTestScore  location
0       abc      mno  12.0    m          90.0           65.0       NaN
1       NaN      NaN   NaN  NaN          90.0            NaN       NaN
2       ghi      pqr  12.0    f           NaN           65.0       NaN
3       jkl      stu  12.0    f          90.0           62.0       NaN
4       mno      vwx  12.0    m          89.0           63.0       NaN

In [9]:
DT.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   FirstName      4 non-null      object 
 1   LastName       4 non-null      object 
 2   Age            4 non-null      float64
 3   Sex            4 non-null      object 
 4   preTestScore   4 non-null      float64
 5   postTestScore  4 non-null      float64
 6   location       0 non-null      float64
dtypes: float64(4), object(3)
memory usage: 412.0+ bytes


In [10]:
 # to identify missing value
DT.isnull()

FirstName  LastName    Age    Sex  preTestScore  postTestScore  location
0      False     False  False  False         False          False      True
1       True      True   True   True         False           True      True
2      False     False  False  False          True          False      True
3      False     False  False  False         False          False      True
4      False     False  False  False         False          False      True

In [11]:
#to identify the number of missing values in each column
DT.isnull().sum()

FirstName        1
LastName         1
Age              1
Sex              1
preTestScore     1
postTestScore    1
location         5
dtype: int64

In [12]:
#to identify columns with at least one missing values
DT.isnull().any(axis=0)

FirstName        True
LastName         True
Age              True
Sex              True
preTestScore     True
postTestScore    True
location         True
dtype: bool

In [13]:
#to identfy columns that have missing values throughout the column
DT.isnull().all(axis=0)

FirstName        False
LastName         False
Age              False
Sex              False
preTestScore     False
postTestScore    False
location          True
dtype: bool

In [14]:
#number of columns with all missing values
DT.isnull().all(axis=0).sum()


1

In [15]:
#rows with at least one missing values
DT.isnull().any(axis=1)

0    True
1    True
2    True
3    True
4    True
dtype: bool

In [16]:
#rows with all missing values
DT.isnull().all(axis=1)

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [17]:
#calculating the percent of null values for each column
DT.isnull().sum()/len(DT.index)*100

FirstName         20.0
LastName          20.0
Age               20.0
Sex               20.0
preTestScore      20.0
postTestScore     20.0
location         100.0
dtype: float64

In [18]:
#the location has 100%, which means that the entire column is made up of null values
#removing the location column

In [19]:
DT.dropna(axis=1, how='all', inplace=True)

In [20]:
DT

FirstName LastName   Age  Sex  preTestScore  postTestScore
0       abc      mno  12.0    m          90.0           65.0
1       NaN      NaN   NaN  NaN          90.0            NaN
2       ghi      pqr  12.0    f           NaN           65.0
3       jkl      stu  12.0    f          90.0           62.0
4       mno      vwx  12.0    m          89.0           63.0

In [21]:
# removing rows
DT[DT.isnull().sum(axis=1)>=4]

FirstName LastName  Age  Sex  preTestScore  postTestScore
1       NaN      NaN  NaN  NaN          90.0            NaN

In [22]:
#retaining the rows having <=4 NaNs
DT =DT[DT.isnull().sum(axis=1)<=4]
DT

FirstName LastName   Age Sex  preTestScore  postTestScore
0       abc      mno  12.0   m          90.0           65.0
2       ghi      pqr  12.0   f           NaN           65.0
3       jkl      stu  12.0   f          90.0           62.0
4       mno      vwx  12.0   m          89.0           63.0

In [23]:
DT.describe()

Age  preTestScore  postTestScore
count   4.0      3.000000           4.00
mean   12.0     89.666667          63.75
std     0.0      0.577350           1.50
min    12.0     89.000000          62.00
25%    12.0     89.500000          62.75
50%    12.0     90.000000          64.00
75%    12.0     90.000000          65.00
max    12.0     90.000000          65.00

In [24]:
DT['preTestScore'].describe()

count     3.000000
mean     89.666667
std       0.577350
min      89.000000
25%      89.500000
50%      90.000000
75%      90.000000
max      90.000000
Name: preTestScore, dtype: float64

In [25]:
#Imputation Using Mean
DT.loc[:, 'preTestScore']= DT['preTestScore'].fillna(DT['preTestScore'].mean())

In [26]:
DT

FirstName LastName   Age Sex  preTestScore  postTestScore
0       abc      mno  12.0   m     90.000000           65.0
2       ghi      pqr  12.0   f     89.666667           65.0
3       jkl      stu  12.0   f     90.000000           62.0
4       mno      vwx  12.0   m     89.000000           63.0

In [27]:
# sk.learn.impute: The Imputation Toolkit in scikit-learn

In [28]:
DT = pd.read_csv('my data/data.csv', na_values=missing_val)
DT

FirstName LastName   Age  Sex  preTestScore  postTestScore  location
0       abc      mno  12.0    m          90.0           65.0       NaN
1       NaN      NaN   NaN  NaN          90.0            NaN       NaN
2       ghi      pqr  12.0    f           NaN           65.0       NaN
3       jkl      stu  12.0    f          90.0           62.0       NaN
4       mno      vwx  12.0    m          89.0           63.0       NaN

In [29]:
#returned only the columns that are numerical
DT_num = DT.select_dtypes(include=['number'])

In [30]:
DT_num

Age  preTestScore  postTestScore  location
0  12.0          90.0           65.0       NaN
1   NaN          90.0            NaN       NaN
2  12.0           NaN           65.0       NaN
3  12.0          90.0           62.0       NaN
4  12.0          89.0           63.0       NaN

In [31]:
# Remove the location col

DT_num2 = DT_num.drop(['location'], axis=1)
DT_num2

Age  preTestScore  postTestScore
0  12.0          90.0           65.0
1   NaN          90.0            NaN
2  12.0           NaN           65.0
3  12.0          90.0           62.0
4  12.0          89.0           63.0

IterativeImputer

In [32]:
#explicitly ask for this experimental feature

from sklearn.experimental import enable_iterative_imputer
#then import the library
from sklearn.impute import IterativeImputer


In [33]:
#initialize it
iterimp =IterativeImputer()

In [34]:
DT_num2

Age  preTestScore  postTestScore
0  12.0          90.0           65.0
1   NaN          90.0            NaN
2  12.0           NaN           65.0
3  12.0          90.0           62.0
4  12.0          89.0           63.0

In [36]:
DT_itermp= pd.DataFrame(iterimp.fit_transform(DT_num2), columns=DT_num2.columns, index =DT_num2.index)
DT_itermp

Age  preTestScore  postTestScore
0  12.0     90.000000      65.000000
1  12.0     90.000000      63.750226
2  12.0     89.751133      65.000000
3  12.0     90.000000      62.000000
4  12.0     89.000000      63.000000

In [37]:
iterimp.fit_transform(DT_num2)

array([[12.        , 90.        , 65.        ],
       [12.        , 90.        , 63.75022648],
       [12.        , 89.75113289, 65.        ],
       [12.        , 90.        , 62.        ],
       [12.        , 89.        , 63.        ]])

SimpleImputer

In [38]:
#import library

#step 1-import the SimplerImputer tool from the sklearn.impute library
from sklearn.impute import SimpleImputer

#from the impute section of the sklearn library, I want you to import the SimpleImputer tool

#step 2-initialize the tool AKA activate the tool
mean_imputer = SimpleImputer(strategy='mean') #you can also use other strategies like median


In [42]:
DT_num2


Age  preTestScore  postTestScore
0  12.0          90.0           65.0
1   NaN          90.0            NaN
2  12.0           NaN           65.0
3  12.0          90.0           62.0
4  12.0          89.0           63.0

In [44]:
DT_impt= pd.DataFrame(mean_imputer.fit_transform(DT_num2), columns=DT_num2.columns, index=DT_num2.index)
DT_impt

Age  preTestScore  postTestScore
0  12.0         90.00          65.00
1  12.0         90.00          63.75
2  12.0         89.75          65.00
3  12.0         90.00          62.00
4  12.0         89.00          63.00

In [45]:
DT_impt.isnull().sum()

Age              0
preTestScore     0
postTestScore    0
dtype: int64

In [46]:
mean_imputer.fit_transform(DT_num2)

array([[12.  , 90.  , 65.  ],
       [12.  , 90.  , 63.75],
       [12.  , 89.75, 65.  ],
       [12.  , 90.  , 62.  ],
       [12.  , 89.  , 63.  ]])

KNNImputer

In [49]:
from sklearn.impute import KNNImputer

#initialize the tool
knn_imputer = KNNImputer(n_neighbors=3)

In [52]:
DT_knn = pd.DataFrame(knn_imputer.fit_transform(DT_num2), columns=DT_num2.columns, index=DT_num2.index)
DT_knn

Age  preTestScore  postTestScore
0  12.0     90.000000      65.000000
1  12.0     90.000000      63.333333
2  12.0     89.666667      65.000000
3  12.0     90.000000      62.000000
4  12.0     89.000000      63.000000

In [53]:
knn_imputer.fit_transform(DT_num2)

array([[12.        , 90.        , 65.        ],
       [12.        , 90.        , 63.33333333],
       [12.        , 89.66666667, 65.        ],
       [12.        , 90.        , 62.        ],
       [12.        , 89.        , 63.        ]])