In [1]:
!pip install numpy

In [7]:
lst = [1,2,3,4,5,6,7,8,9]

In [9]:
print(type(lst))

<class 'list'>


In [11]:
print("List: ", lst)

List:  [1, 2, 3, 4, 5, 6, 7, 8, 9]


In [13]:
import numpy as np
arr_my = np.array(lst)

In [15]:
print(type(arr_my))

<class 'numpy.ndarray'>


In [17]:
print(arr_my)

[1 2 3 4 5 6 7 8 9]


In [19]:
print("numpy array: ", arr_my)

numpy array:  [1 2 3 4 5 6 7 8 9]


In [23]:
arr_Cv = np.arange(40)
print(type(arr_Cv))
print(arr_Cv)

<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [3]:
%%time
lst = list(range(1000000))
for i in range(1000000):
    lst[i]*lst[i]


CPU times: total: 625 ms
Wall time: 842 ms


In [1]:
import numpy as np

arr = np.array([[1,2,3,4], [3,4,5,6]])

print(f'Array: {arr}')

print()

Array: [[1 2 3 4]
 [3 4 5 6]]



In [3]:
print(arr.shape)

(2, 4)


In [5]:
print("DIM: ", arr.shape)

DIM:  (2, 4)


In [7]:
print('Data type: ', arr.dtype)

Data type:  int32


In [11]:
print('item size: ', arr.itemsize)
print('dimensionality: ', arr.ndim)


item size:  4
dimensionality:  2


In [13]:
arr = np.arange(2,16)

In [17]:
print('Array: ', arr)
print('Shape: ', arr.shape)

Array:  [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Shape:  (14,)


In [21]:
arr = np.arange(1,13, 3)
print(arr)

[ 1  4  7 10]


In [23]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)

    Return evenly spaced values within a given interval.

    ``arange`` can be called with a varying number of positional arguments:

    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.

    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.

    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.

    See the Warning sections 

In [27]:
arr = np.ones((5,3))


In [29]:
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
print(arr.shape)

(5, 3)


In [33]:
print(arr.dtype)

float64


In [35]:
arr = np.random.rand(5)

In [41]:
print(arr)

[0.37673298 0.92183286 0.43949851 0.62231886 0.70367961]


In [43]:
arr = np.random.randn(6)
print(arr)

[-1.26856676  1.21007958 -0.05138834  1.20954857  0.62858003  0.45257638]


In [45]:
arr = np.random.randint(10)
print(arr)

3


In [47]:
print(arr)

3


In [49]:
print(arr)

3


In [63]:
arr = np.random.randint(10, size = (5,5))
print("Array: ", arr)

Array:  [[0 1 4 2 2]
 [3 6 8 1 7]
 [6 2 5 8 6]
 [1 8 2 7 0]
 [4 8 0 8 4]]


In [69]:
arr = np.random.randint(10, size = (5,4))

print('Array: \n', arr)

Array: 
 [[1 2 5 3]
 [2 6 5 5]
 [3 6 3 3]
 [7 4 4 1]
 [7 0 1 6]]


In [71]:
arr = np.random.randint(10)
print(arr)

6


In [73]:
arr = np.random.randint(100)
print(arr)

5


In [75]:
print(arr)

5


In [79]:
arr = np.random.randint(100)
print(arr)

47


In [81]:
arr = np.random.randint(100, size = (5,6))
print(arr)

[[49 13 86  2  9 57]
 [79 49 99 68 18 28]
 [33 61 82 72 85 71]
 [70 89 43 98 66 79]
 [ 2 58 95 82 15 81]]


In [83]:
print('Array: ', arr)

Array:  [[49 13 86  2  9 57]
 [79 49 99 68 18 28]
 [33 61 82 72 85 71]
 [70 89 43 98 66 79]
 [ 2 58 95 82 15 81]]


In [85]:
print('Array: \n', arr)

Array: 
 [[49 13 86  2  9 57]
 [79 49 99 68 18 28]
 [33 61 82 72 85 71]
 [70 89 43 98 66 79]
 [ 2 58 95 82 15 81]]


In [87]:
print(arr[0])
print(arr[3])

[49 13 86  2  9 57]
[70 89 43 98 66 79]


In [93]:
print(arr[0,3])
print(arr[2,4])

2
85


In [97]:
    print(arr[3][2])

43


In [101]:
print(arr[3,2])

43


In [109]:
arr = np.random.randint(100, size = (5,5))
print(arr)

[[62 19  1  3 61]
 [82 48 18 56 66]
 [47 48 86 36 30]
 [29 85 24 22  1]
 [44 19 54 92  3]]


In [111]:
print('Array: \n', arr)

Array: 
 [[62 19  1  3 61]
 [82 48 18 56 66]
 [47 48 86 36 30]
 [29 85 24 22  1]
 [44 19 54 92  3]]


In [115]:
arr[0,2] =100
arr[3, 4] = 50
print(arr)

[[ 62 100 100   3  61]
 [ 82  48  18  56  66]
 [ 47  48  86  36  30]
 [ 29  85  24  22  50]
 [ 44  19  54  92   3]]


In [119]:
arr = np.random.randint(10, 40, size = (4,5))

In [121]:
print(arr)

[[25 23 38 17 14]
 [36 16 20 17 12]
 [23 16 38 34 24]
 [11 12 22 19 31]]


In [123]:
# print(arr[::2])

[[25 23 38 17 14]
 [23 16 38 34 24]]


In [125]:
# arr = arr.flatten()
# print(arr)

[25 23 38 17 14 36 16 20 17 12 23 16 38 34 24 11 12 22 19 31]


In [129]:
# arr = arr.ravel()
# print(arr)

[25 23 38 17 14 36 16 20 17 12 23 16 38 34 24 11 12 22 19 31]


In [131]:
print(arr)

[25 23 38 17 14 36 16 20 17 12 23 16 38 34 24 11 12 22 19 31]


In [133]:
arr = np.random.randint(10, 40, size = (4,5))

In [135]:
print(arr)

[[34 18 14 29 11]
 [23 23 18 24 34]
 [19 16 32 13 38]
 [12 19 29 25 20]]


In [143]:
print('Array: \n', arr)

Array: 
 [[34 18 14 29 11]
 [23 23 18 24 34]
 [19 16 32 13 38]
 [12 19 29 25 20]]


In [8]:
arr = np.random.randint(20, 60, size = (5,8))
print('Array: \n', arr)

NameError: name 'np' is not defined

In [7]:
!pip install numpy

In [10]:
arr = np.random.randint(30)

NameError: name 'np' is not defined

In [12]:
import numpy as np

In [14]:
arr = np.random.randint(30)

In [16]:
print(arr)

21


In [20]:
arr = np.random.randint(30, 100, size = (10,))
print(arr)

[65 69 58 38 90 40 73 81 75 41]


In [22]:
arr1 = np.random.randint(10,49, size = (10,))

In [24]:
print(arr1)

[15 20 42 25 18 14 27 25 35 31]


In [28]:
for i in arr1:
    print(i, sep = ',')

15
20
42
25
18
14
27
25
35
31


In [30]:
arr1 = np.random.randint(10, 100, size = (6, 8))
print(arr1)

[[53 87 25 11 63 34 85 20]
 [22 73 78 79 20 69 67 70]
 [82 22 55 87 20 15 15 67]
 [14 85 96 91 73 38 81 54]
 [41 69 68 80 98 32 45 17]
 [33 81 96 75 25 41 26 28]]


In [32]:
print('Array: \n', arr1)
print('Shape:', arr1.shape)

Array: 
 [[53 87 25 11 63 34 85 20]
 [22 73 78 79 20 69 67 70]
 [82 22 55 87 20 15 15 67]
 [14 85 96 91 73 38 81 54]
 [41 69 68 80 98 32 45 17]
 [33 81 96 75 25 41 26 28]]
Shape: (6, 8)


In [34]:
for Ary in arr1:
    print(Ary)

[53 87 25 11 63 34 85 20]
[22 73 78 79 20 69 67 70]
[82 22 55 87 20 15 15 67]
[14 85 96 91 73 38 81 54]
[41 69 68 80 98 32 45 17]
[33 81 96 75 25 41 26 28]


In [36]:

for item in arr1.ravel():
    print(item, end = ' ')

53 87 25 11 63 34 85 20 22 73 78 79 20 69 67 70 82 22 55 87 20 15 15 67 14 85 96 91 73 38 81 54 41 69 68 80 98 32 45 17 33 81 96 75 25 41 26 28 

In [38]:
print(arr1)

[[53 87 25 11 63 34 85 20]
 [22 73 78 79 20 69 67 70]
 [82 22 55 87 20 15 15 67]
 [14 85 96 91 73 38 81 54]
 [41 69 68 80 98 32 45 17]
 [33 81 96 75 25 41 26 28]]


In [42]:
help(np.nditer)

Help on class nditer in module numpy:

class nditer(builtins.object)
 |  nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K', casting='safe', op_axes=None, itershape=None, buffersize=0)
 |
 |  Efficient multi-dimensional iterator object to iterate over arrays.
 |  To get started using this object, see the
 |  :ref:`introductory guide to array iteration <arrays.nditer>`.
 |
 |  Parameters
 |  ----------
 |  op : ndarray or sequence of array_like
 |      The array(s) to iterate over.
 |
 |  flags : sequence of str, optional
 |        Flags to control the behavior of the iterator.
 |
 |        * ``buffered`` enables buffering when required.
 |        * ``c_index`` causes a C-order index to be tracked.
 |        * ``f_index`` causes a Fortran-order index to be tracked.
 |        * ``multi_index`` causes a multi-index, or a tuple of indices
 |          with one per iteration dimension, to be tracked.
 |        * ``common_dtype`` causes all the operands to be converted to
 |     

Iterating using np.nditer()

In [49]:
for Tem in np.nditer(arr):
    print(Tem, sep = ',')

65
69
58
38
90
40
73
81
75
41


In [51]:
for Tem in np.nditer(arr):
    print(Tem, end = ' ')

65 69 58 38 90 40 73 81 75 41 

In [63]:
for Tem1 in np.nditer(arr1):
    print(Tem1, sep = '')

53
87
25
11
63
34
85
20
22
73
78
79
20
69
67
70
82
22
55
87
20
15
15
67
14
85
96
91
73
38
81
54
41
69
68
80
98
32
45
17
33
81
96
75
25
41
26
28


In [59]:
    print(Tem1, end = ' ')

28 

In [61]:
for Tem1 in np.nditer(arr1):
    print(Tem1, end = ' ')

53 87 25 11 63 34 85 20 22 73 78 79 20 69 67 70 82 22 55 87 20 15 15 67 14 85 96 91 73 38 81 54 41 69 68 80 98 32 45 17 33 81 96 75 25 41 26 28 

Exercise 1
Write a program to generate an array with shape 5 by 4 at random containing positive integers. Perform an update by replacing all odd numbers using -1 (Using a loop)

In [67]:
ARY = np.random.randint(50, size = (5,4))
print('Arr: \n',ARY)

Arr: 
 [[21 14 45  9]
 [13  1  0 10]
 [12  5 21 15]
 [18 39 36 41]
 [48 23 44 20]]


In [73]:
for TEM in np.nditer(ARY, op_flags = ['readwrite']):
    if TEM%2 !=0:
        TEM[...] = -1
print('Final_Reat: \n', ARY)

Final_Reat: 
 [[-1 14 -1 -1]
 [-1 -1  0 10]
 [12 -1 -1 -1]
 [18 -1 36 -1]
 [48 -1 44 20]]


Exercise 2
Given an array [1, -10, 2,3,0,6], print the array in this order [0,6,-10,2,1,3]

In [75]:
array1 = np.array([1,-10, 2,3,0,6])

array2 = np.concatenate((array1[4:6], array1[1:3], np.array([array1[0]]), np.array([array1[3]])))

array2

array([  0,   6, -10,   2,   1,   3])

Python Operators on Numpy Array


In [80]:
x = np.array([[1,2,5,7,4], [4,7,8,9,0]])

In [82]:
print('New_X: \n', x)

New_X: 
 [[1 2 5 7 4]
 [4 7 8 9 0]]


In [88]:
print('Asum: \n', x+4)
print('AmD: \n', x%2)
print('AMU: \n', x*2)

Asum: 
 [[ 5  6  9 11  8]
 [ 8 11 12 13  4]]
AmD: 
 [[1 0 1 1 0]
 [0 1 0 1 0]]
AMU: 
 [[ 2  4 10 14  8]
 [ 8 14 16 18  0]]


In [90]:
print(x >=3)

[[False False  True  True  True]
 [ True  True  True  True False]]


Exercise3

Write a program to generate an array with shape 5 by 4 at random containing positive integer. Perform an update by replacing all odd numbers with -1. (Without using a Loop)

In [96]:
GENM = np.random.randint(50, size = (5,4))
print(GENM)

[[34  5 37 35]
 [10 33 27  3]
 [22 33 40 30]
 [ 5 17 41  9]
 [47 49 47  2]]


In [98]:
index = (GENM%2!=0)
index

array([[False,  True,  True,  True],
       [False,  True,  True,  True],
       [False,  True, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True, False]])

In [100]:
arr_copy = GENM.copy()

arr_copy[index] = -1
arr_copy

array([[34, -1, -1, -1],
       [10, -1, -1, -1],
       [22, -1, 40, 30],
       [-1, -1, -1, -1],
       [-1, -1, -1,  2]])

In [102]:
arr_copy2 = GENM.copy()
arr_copy2

array([[34,  5, 37, 35],
       [10, 33, 27,  3],
       [22, 33, 40, 30],
       [ 5, 17, 41,  9],
       [47, 49, 47,  2]])

In [106]:
ary = np.random.randint(50, 100, size = (5,10))
ary

array([[50, 59, 76, 98, 72, 57, 58, 78, 65, 87],
       [65, 66, 78, 67, 55, 90, 58, 80, 51, 70],
       [89, 95, 96, 93, 58, 74, 77, 93, 50, 64],
       [97, 91, 53, 52, 69, 97, 64, 62, 55, 99],
       [73, 54, 68, 52, 61, 58, 88, 53, 93, 93]])

In [108]:
np.sort(ary, axis = 0)
np.sort(ary, axis =1)

array([[50, 57, 58, 59, 65, 72, 76, 78, 87, 98],
       [51, 55, 58, 65, 66, 67, 70, 78, 80, 90],
       [50, 58, 64, 74, 77, 89, 93, 93, 95, 96],
       [52, 53, 55, 62, 64, 69, 91, 97, 97, 99],
       [52, 53, 54, 58, 61, 68, 73, 88, 93, 93]])

Task - Dice Rolling Simulation
Create a simulation of a dice rolling game using NumPy. The game will involve rolling two dice and calculating the sum of their values. Players will guess whether the next roll will result in a higher, lower, or equal sum compared to the previous roll. The simulation will track the player's score based on their guesses.

In [ ]:
#number of rounds in the game
num_of_rounds = 4

#range of possible values for the die roll
min_value = 1
max_value = 6

#intializing player's score
score = 0

#a list to record the dice sums
sums_list = []

while num_of_rounds >0 :
    rolling = str(input('\nType "roll": '))


    if rolling == 'roll':
        rolls_array = np.random.randint(min_value, max_value+1, size = (2,))
        dice_sums = np.sum(rolls_array)
        print ("Dice sum:", dice_sums)
        sums_list.append(dice_sums)

        if len(sums_list) > 1:
            if (guess == 'higher' and (sums_list[-1] > sums_list[-2])) or \
               (guess == 'lower' and (sums_list[-1] < sums_list[-2])) or \
               (guess == 'equal' and (sums_list[-1] == sums_list[-2])):
                print('Correct guess!\n')
                score += 1
            else:
                print('Incorrect guess!\n')

    else:
        print('Please type "roll".')



    print('\nWill the next sum be higher, lower, or equal?')

    guess = str(input()).strip().lower()

    if guess not in ["higher", "lower", "equal"]:
        print("Invalid input! Please enter 'higher', 'lower', or 'equal'.")

    num_of_rounds -= 1

else:
    print('\nRounds exhausted! Come back later\n')
    print('View of dice rolls: ', sums_list)
    print('Your total score:', score)


Type "roll":  4


Please type "roll".

Will the next sum be higher, lower, or equal?
